src/Entity/Cart.php
<?php

namespace App\Entity;

use App\Repository\CartRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CartRepository::class)]
class Cart
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'carts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?SweatVariant $SweatVariant = null;

    #[ORM\ManyToOne(inversedBy: 'carts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Customer $customer = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSweatVariant(): ?SweatVariant
    {
        return $this->SweatVariant;
    }

    public function setSweatVariant(?SweatVariant $SweatVariant): static
    {
        $this->SweatVariant = $SweatVariant;

        return $this;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): static
    {
        $this->customer = $customer;

        return $this;
    }
}

src/Entity/Sweat.php
<?php

namespace App\Entity;

use App\Repository\SweatRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SweatRepository::class)]
class Sweat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?bool $top = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $file_name = null;

    /**
     * @var Collection<int, SweatVariant>
     */
    #[ORM\OneToMany(targetEntity: SweatVariant::class, mappedBy: 'sweat', orphanRemoval: true, cascade: ['persist'])]
    private Collection $sweatVariants;

    public function __construct()
    {
        $this->sweatVariants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function isTop(): ?bool
    {
        return $this->top;
    }

    public function setTop(bool $top): static
    {
        $this->top = $top;

        return $this;
    }

    public function getFileName(): ?string
    {
        return $this->file_name;
    }

    public function setFileName(?string $file_name): static
    {
        $this->file_name = $file_name;

        return $this;
    }

    /**
     * @return Collection<int, SweatVariant>
     */
    public function getSweatVariants(): Collection
    {
        return $this->sweatVariants;
    }

    public function addSweatVariant(SweatVariant $sweatVariant): static
    {
        if (!$this->sweatVariants->contains($sweatVariant)) {
            $this->sweatVariants->add($sweatVariant);
            $sweatVariant->setSweat($this);
        }

        return $this;
    }

    public function removeSweatVariant(SweatVariant $sweatVariant): static
    {
        if ($this->sweatVariants->removeElement($sweatVariant)) {
            // set the owning side to null (unless already changed)
            if ($sweatVariant->getSweat() === $this) {
                $sweatVariant->setSweat(null);
            }
        }

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Form\RemoveCartType;
use App\Repository\CartRepository;
use App\Service\StripeService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class CartController extends AbstractController
{
    #[Route('/cart', name: 'app_cart')]
    #[IsGranted('ROLE_USER')]
    public function index(Request $request, EntityManagerInterface $em, CartRepository $cartRepository, FormFactoryInterface $formFactory): Response
    {
        $cartProducts = $cartRepository->findWithSweatAndSizeByCustomer($this->getUser());
        
        $allCartForms = [];
        $allCartFormsViews = [];
        $totalPrice = 0;

        // Create all forms
        foreach ($cartProducts as $cartProduct) {
            $form = $formFactory->createNamed(
                'form_cart_' . $cartProduct->getId(),
                RemoveCartType::class,
                $cartProduct
            );
            $form->handleRequest($request);
            $allCartForms[$cartProduct->getId()] = $form;
            $allCartFormsViews[$cartProduct->getId()] = $form->createView();
            $totalPrice += $cartProduct->getSweatVariant()->getSweat()->getPrice();
        }

        // Manage submission form
        foreach ($allCartForms as $id => $form) {
            if ($form->isSubmitted() && $form->isValid()) {
                $cartProduct = $form->getData();
                $em->remove($cartProduct);
                $em->flush();
                $this->addFlash('success', "Le sweat " . $cartProduct->getSweatVariant()->getSweat()->getName() . " de taille " . strtoupper($cartProduct->getSweatVariant()->getSize()->getSize()) . " a bien été retiré du panier");
                return $this->redirectToRoute("app_cart");
            }
        }

        return $this->render('cart/index.html.twig', [
            'allCartForms' => $allCartFormsViews ?? [],
            'totalPrice' => $totalPrice,
            'publicKey' => $this->getParameter('stripe_public_key'),
        ]);
    }

    #[Route('/cart-payment', name:'app_cart_payment')]
    #[IsGranted('ROLE_USER')]
    public function cartPayment(CartRepository $cartRepository, StripeService $stripeService): JsonResponse
    {
        $cartProducts = $cartRepository->findWithSweatAndSizeByCustomer($this->getUser());

        // Set amount to pay
        $totalPrice = 0;
        foreach ($cartProducts as $cartProduct) {
            $totalPrice += $cartProduct->getSweatVariant()->getSweat()->getPrice();
        } 
        $amount = (int) round($totalPrice*100); // $amount is in cents

        $paymentIntent = $stripeService->createPaymentIntent($amount);

        return new JsonResponse([
            'clientSecret' => $paymentIntent->client_secret,
        ]);
    }

    #[Route('/cart-payment-confirmed', name:'app-cart-payment-confirmed')]
    #[IsGranted('ROLE_USER')]
    public function cartPaymentConfirmed(CartRepository $cartRepository, EntityManagerInterface $em): JsonResponse
    {
        // Empty the cart now products have been payed
        $cartProducts = $cartRepository->findBy(['customer' => $this->getUser()]);
        foreach ($cartProducts as $cartProduct) {
            $em->remove($cartProduct);
            $em->flush();
            // Next step is to create an Order Entity to save the orders
        }
        $this->addFlash('success', "Le paiement est validé, nous vous remercions pour votre achat");
        return new JsonResponse([
            'success' => true
        ]);
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://js.stripe.com/v3/"></script>
{% endblock %}

{% block importmap %}
    {{ parent() }}
    {{ importmap('controllers/cart') }}
{% endblock %}

{% block main %}
<main>
    {% for message in app.flashes('success') %}
        <p class='flash-success'>{{ message }}</p>
    {% endfor %}
    {% for cartForm in allCartForms %}
        {{ form_start(cartForm, {'attr': {'class': 'remove-cart-form'}}) }}
            <img class="remove-cart-form__image" src="{{ asset(cartForm.vars.value.SweatVariant.sweat.fileName) }}" alt="a sweat photo">
            <div class="remove-cart-form__content">
                <div class="remove-cart-form__info">
                    <p class="remove-cart-form__name">{{ cartForm.vars.value.SweatVariant.sweat.name }}</p>
                    <p class="remove-cart-form__price">{{ cartForm.vars.value.SweatVariant.sweat.price|number_format(2, ',', ' ') }} €</p>
                    <p class="remove-cart-form__size">Taille : {{ cartForm.vars.value.SweatVariant.size.size|upper }}</p>
                </div>
                {{ form_widget(cartForm.submit, {'attr': {'class': 'remove-cart-form__button'}}) }}
            </div>
        {{ form_end(cartForm) }}
    {% endfor %}
    <section class="card-actions">
        <p class="card-actions__total-price">TOTAL : {{ totalPrice|number_format(2, ',', ' ') }} €</p>
        <div class="card-actions__buttons">
            <button class="card-actions__button card-actions__button--payment modal-toggle">Finaliser ma commande</button>
            <a href="{{ path('app_all_products') }}" class="card-actions__button card-actions__button--keep-shopping">Continuer mes achats</a>  
        </div>
    </section>
    <div id='stripe-public-key' data-public-key="{{ publicKey }}"></div>
    <div id="payment-modal" class="modal hidden-modal">
        <div class="modal__overlay modal-toggle"></div>
        <div class="modal__content">
            <span class="modal__close modal-toggle">&times;</span>
            <h2 class="modal__title">Paiement sécurisé</h2>
            <form action="#" id="payment-form" class="modal__form">
                <div id="card-element"></div>
                <div id="userName" data-name="{{ app.user.name }}"></div>
                <button id="sumbit-payment" class="modal__button" type="submit">Payer</button>
            </form>
        </div>
    </div>
</main>
{% endblock %}